##############################################################################
#                                                                            #
#                                                                            #
#     Below are common commands that you'd use while inside the cluster.     #
#                                                                            #
#                                                                            #
##############################################################################

# copy folder to your machine
scp user.name@talc.ucalgary.ca:/work/TALC/enel645_2024w/CVPR_2024_dataset .